### ISSUE TITLE
Doesn't work on Mac Chrome

### ISSUE THREAD

**Issue by paweb** [Amphiluke/handy-scroll#3] opened 2019-11-13 11:25 UTC
Handy-scroll doesn't work on Chrome (78.0.3904.70) on OS X (10.14.6) if the setting `System preferences` > `General` > `Show scroll bars` is something else than `Always`.

Tested with the demo:
https://amphiluke.github.io/handy-scroll/

**Expected result:**
Scrollbar is visible always while scrolling even though the bottom of the container is not visible.

**Actual result:**
Scrollbar is visible only when the bottom of the container is visible.

**Comment by Amphiluke** [comment] 2019-11-13 17:14
Hello @paweb 
Actually, I think, this is rather _expected_ behavior. If I switch off scroll bar visibility in system settings, then I do not expect floating scroll bar to stay visible ignoring my system preferences.

**Comment by paweb** [comment] 2019-11-13 19:52
Hello @Amphiluke 

I didn't mean that the scrollbar should stay visible, I just meant, it should be visible while scrolling. Now, it's not visible always on scrolling on Chrome. Anyway, on Safari and Firefox, it is visible so then my question is, why it behaves differently on Mac's Safari and Firefox compared to Chrome?

Whatever is the expected behavior, I think, it should be consistent between browsers.

**Comment by Amphiluke** [comment] 2019-11-14 02:46
Ah, got it, thanks. Well, it looks like this is caused by that the widget tries to get native scroll bar height programmatically (to avoid hard-coding some empirical value). This makes widget’s height equal to 1px, when scroll bars are initially hidden. BTW, for me, Safari on Mac OS is also affected by the issue…

I will try to handle this case this week and publish the fix with a new release.

**Comment by paweb** [comment] 2019-11-14 05:35
Good, thanks! I also saw the issue on Mac OS Safari, but then all of a sudden it disappeared and worked normally.

**Comment by Amphiluke** [comment] 2019-11-16 16:03
This issue will have purely CSS solution. You may find it [here](https://github.com/Amphiluke/handy-scroll/commit/bccef9d1d2c1087efec11ee3857072b223021234#diff-75d7a2cd4ba35558f9d0df4657ca9658R3). Unfortunately, the release of a new version might be a bit delayed because there is another unrelated [bug](https://github.com/Amphiluke/floating-scroll/issues/17) that should be fixed in the upcoming version. It may take a while. Anyway, until the update is published, you may fix current issue yourself, adding the following in your style sheet:
```css
body .handy-scroll {
    min-height: 17px;
}
```

**Comment by Amphiluke** [comment] 2019-11-17 13:31
The widget’s [new version 1.0.5](https://github.com/Amphiluke/handy-scroll/releases/tag/v1.0.5) has been released. The updated package is available on npm too.

@paweb, thanks for reporting! :+1:

**Closed** 2019-11-17 13:31 UTC
Labels: bug

**Comment by paweb** [comment] 2019-11-18 08:14
Thanks for the quick fix! 👍
